### ISSUE TITLE
problems with joomla version 3.6.2

### ISSUE THREAD

**Issue by Richardkl** [mokhin-denis/plg_system_askmyadmin#1]
I just updated to Joomla 3.6.2 and when I tried to log into backend I got this error
Failed to start the session because headers have already been sent by "/var/sentora/hostdata/elite/public_html/........./plugins/system/askmyadmin/askmyadmin.php" at line 77. 

I had to go into phpmyadmin and disable askmyadmin

**Comment by mokhin-denis** [comment]
Can you please test with other website J3.6.2? My websites on J3.6.2 works fine (check out http://funnymath.ru/administrator or http://stomat-mk.ru/administrator/) Are u sure u have update Joomla correctly?

**Comment by mokhin-denis** [comment]
Try to re-install plug-in please

**Comment by Richardkl** [comment]
I upgraded another web site to 3.6.0 and this is the error I get when login into administrator using version 1.2  also same problem with version 1.3
but still able to get to back-end admin web site

PHP Strict Standards:  Only variables should be assigned by reference in /var/sentora/hostdata/elite/public_html/..../plugins/system/askmyadmin/askmyadmin.php on line 77, 
But still able to access back-end admin page

Now upgraded web site to 3.6.2 and this is the error I get when login into administrator I get this error
and cant login to admin page
Failed to start the session because headers have already been sent by "/var/sentora/hostdata/elite/public_html/....../plugins/system/askmyadmin/askmyadmin.php" at line 77. 
Now not able to get to back-end admin web site
php5.6
ubuntu 16.04

global configuration Error Reporting set to development

NOTE:
I found out when I set the global configuration Error Reporting set to none I am then able to access the back-end administration web page with no problem

**Comment by mokhin-denis** [comment]
Could you check "Extensions - Manage - Database" menuitem on both your Joomla sites, please? Is it OK? You should see:

Notice
Database table structure is up to date.

**Comment by Richardkl** [comment]
```
Other Information

Database schema version (in #__schemas): 3.6.0-2016-06-05.
Update version (in #__extensions): 3.6.2.
Database driver: mysqli.
98 database changes were checked successfully.
158 database changes did not alter table structure and were skipped

Other Information

Database schema version (in #__schemas): 3.6.0-2016-06-05.
Update version (in #__extensions): 3.6.2.
Database driver: mysqli.
98 database changes were checked successfully.
158 database changes did not alter table structure and were skipped
```

checked both databases all ok but clicked fix anyway, turned php error reporting back on to development and got the error

An error has occurred.

```
0 Failed to start the session because headers have already been sent by "/var/sentora/hostdata/elite/public_html/kent1_com/plugins/system/askmyadmin/askmyadmin.php" at line 77. 
```

Return to Control Panel

when I click on return to control panel It goes the the default web site I have programed in your asmyadmin plugin

**Comment by mokhin-denis** [comment]
Can u please try this file

[askmyadmin.php.zip](https://github.com/mokhin-denis/plg_system_askmyadmin/files/444521/askmyadmin.php.zip)

Unzip and replace at /var/sentora/hostdata/elite/public_html/kent1_com/plugins/system/askmyadmin/askmyadmin.php

**Comment by Richardkl** [comment]
Worked perfect, no errors even with global configuration Error Reporting set to development
