### ISSUE TITLE
не работает с Joomla 3.6.2

### ISSUE THREAD

**Issue by vadim2017** [mokhin-denis/plg_system_askmyadmin#2]
Обновил Joomla до версии 3.6.2, плагин перестал работать. Адрес входа стал стандартным. Что делать?

**Comment by mokhin-denis** [comment]
1. Можете проверить на другой установке Joomla 3.6.2 с включенным выводом ошибок PHP?
2. У вас актуальная версия плагина?

**Comment by vadim2017** [comment]
1. Я не великий специалист. Больше пользователь. Ошибок не выдает, просто как будто не видит плагина и оставляет вход в админку стандартный.2. Вроде актуальная, 1.3, скачано с gethub.

Отправлено с устройства Samsung

-------- Исходное сообщение --------
От: Denis Mokhin notifications@github.com 
Дата: 26.08.2016  12:20  (GMT+03:00) 
Кому: mokhin-denis/plg_system_askmyadmin plg_system_askmyadmin@noreply.github.com 
Копия: vadim2017 v-shkoda@yandex.ru, Author author@noreply.github.com 
Тема: Re: [mokhin-denis/plg_system_askmyadmin] не работает с Joomla 3.6.2 (#2) 

Можете проверить на другой установке Joomla 3.6.2 с включенным выводом ошибок PHP?
У вас актуальная версия плагина?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mokhin-denis/plg_system_askmyadmin","title":"mokhin-denis/plg_system_askmyadmin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mokhin-denis/plg_system_askmyadmin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mokhin-denis in #2: 1. Можете проверить на другой установке Joomla 3.6.2 с включенным выводом ошибок PHP?\r\n2. У вас актуальная версия плагина?"}],"action":{"name":"View Issue","url":"https://github.com/mokhin-denis/plg_system_askmyadmin/issues/2#issuecomment-242676943"}}}

**Comment by mokhin-denis** [comment]
1. У вас есть доступ к настройкам PHP? Включите там вывод ошибок
2. Попробуйте удалить плагин и установить заново
3. Joomla обновилась без ошибок?

**Comment by vadim2017** [comment]
Повторно переустановил - заработало. Спасибо!

**Comment by mokhin-denis** [comment]
Здорово! Буду признателен, если оставите отзыв на http://extensions.joomla.org/extensions/extension/search-a-indexing/tags-a-clouds/mytags

**Comment by vadim2017** [comment]
Странно, через день начало выбрасывать
Failed to start the session because headers have already been sent by ".../public_html/plugins/system/askmyadmin/askmyadmin.php" at line 77

**Comment by mokhin-denis** [comment]
1. Какая версия PHP?
2. Идем в "Расширения - Менеджер расширений - База данных". Что у вас со структурой БД?

**Comment by vadim2017** [comment]
PHP 5.6.23, после обновления Joomla до 3.6.2 начал выдавать ошибки при попытке загрузки расширений. На странице ПРЕДУПРЕЖДЕНИЯ запись:"Каталог временных файлов Joomla! недоступен для записи или не существует по указанному адресу, что может вызвать проблемы при попытке загрузить расширения..."
Вообщем я восстановил Joomla 3.5.1, доступ появился. Возможно дело и не в вашем приложении, а в кривом обновлении.

**Comment by mokhin-denis** [comment]
Значит, нужно обновить-таки правильно Joomla до актуальной версии. Могу помочь с советами. Пишите лично на почту. Issue пока снова закрываю, как неимеющее бод собой основания.
