### ISSUE TITLE
askmyadmin не впускает хозяина

### ISSUE THREAD

**Issue by ramanzes** [mokhin-denis/plg_system_askmyadmin#3]
После Успешного входа в приглашение залогиниться в админке, независимо от результата перенаправляет на указанную страницу 
редиректа. причём это происходило не всегда, а иногда, учитывая что пароль и логин сохранены в браузере. после обновления 10-й винды, это происходит всегда, как устранить эту проблему? простое переименование папки askmyadmin убирает редирект, но в админку всё равно не пускает

**Comment by mokhin-denis** [comment]
Давайте по-порядку.
1. Актуальная ли версия Joomla?
2. Актуальная ли структура БД?
3. Актуальная ли версия AskMyAdmin?

Если на все вопросы ответ утвердительный - идите в базу напрямую, ищите таблицу #__extensions, там ищете строку расширения askmyadmin и в столбце published ставите 0. После этого вам будет свободный вход.
