### ISSUE TITLE
Проблема с плагином

### ISSUE THREAD

**Issue by Mikhael007** [mokhin-denis/plg_system_askmyadmin#4]
Здравствуйте! У меня убойная проблема с плагином. После удаления старой версии AScMyAdmin и попытки установки новой сайт слетел полностью. Нельзя войти в админку и просто на сайт: Страница недоступна
Сайт lafit-centr.ru пока не может обработать этот запрос.
HTTP ERROR 500. Техподдержка на хостинге пишет следующее: Согласно логу PHP ошибка в коде сайта. По данному вопросу необходимо обратиться к разработчикам.

[20-Mar-2018 18:06:17 Europe/Moscow] PHP Notice:  Use of undefined constant azx101d5_lafit - assumed 'azx101d5_lafit' in /home/a/azx101d5/lafit-centr.ru/public_html/includes/framework.php on line 56
[20-Mar-2018 18:06:17 Europe/Moscow] PHP Fatal error:  Call to undefined method JSite::isClient() in /home/a/azx101d5/lafit-centr.ru/public_html/plugins/system/askmyadmin/askmyadmin.php on line 68
Самого плагина я в соответствующей папке не нашёл (думал попробовать удаление). Никакие решения не помогают. Не подскажете в чём может быть проблема?

**Comment by mokhin-denis** [comment]
Для начала необходимы некоторые технические данные:

1. Какая версия плагина стояла до удаления?
2. Какая текущая версия Joomla, PHP, MySQL?
3. Менялись ли кроме версии плагина также и версии Joomla, PHP, MySQL?
4. Если да, то какие были версии Joomla, PHP, MySQL до обновления?
5. Есть ли доступ к админке сайта?
6. Есть ли доступ к файлам сайта по FTP?
7. Есть ли доступ к БД сайта через phpmyadmin?

**Comment by Mikhael007** [comment]
Уже сам разобрался. Там старая джумла 2.5. стояла, а плагин такой же. Когда сайт рухнул я догадался папку удалить через файлы, раз в админку входа не было, но не помогло. А потом догадался ещё раз поискать и там почему-то опять оказалась папка askmyadmin. Теперь всё нормально. Спасибо
