### ISSUE TITLE
Не работает с joomla 3.3.3

### ISSUE THREAD

**Issue by TYMON99** [mokhin-denis/plg_system_askmyadmin#5]
Здравствуйте. Почему-то не срабатывает плагин на Joomla версии 3.3.3, устанавливается - пишет, что успешно, заполняем - сохраняется. Но доступ к сайту по пути /administrator всё равно доступен. В чем может быть проблема?

**Comment by mokhin-denis** [comment]
Здравствуйте. А вы активировали плагин?

**Comment by TYMON99** [comment]
В смысле что включен плагин или нет? То включен. Или как надо активировать?

**Comment by mokhin-denis** [comment]
Да. После установки плагина, настройте его. Убедитесь, что он включен.

**Comment by TYMON99** [comment]
Да, поля заполнены, плагин включен. Может ли это быть связано, что сайт работает по https: а не по http: ?

**Comment by mokhin-denis** [comment]
Не уверен. Проверю на своем сайте, напишу здесь, если терпит.

**Comment by TYMON99** [comment]
Да терпит, конечно)

**Comment by TYMON99** [comment]
Ещё заметил, что при включении плагина, кроме как на страницу /administrator, не заходит на сайт, просто белая страница

**Comment by mokhin-denis** [comment]
Проверил сейчас на одном из своих сайтов. Например [здесь](https://funnymath.ru). Работает. Есть SSL в том числе. Поэтому, настоятельно рекомендую для работы с плагином:

1.  Обновить Joomla! до актуальной версии 3.9.0
2. Установить плагин из [магазина](https://extensions.joomla.org/extension/askmyadmin/) или скачать [отсюда](https://github.com/mokhin-denis/plg_system_askmyadmin/releases/latest).
